name = "Strawberry"
# grammar = "strawberry"
path_suffixes = ["str"]
line_comments = ["//"]
tab_size = 4
hard_tabs = false
autoclose_before = ")}]"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false },
    { start = "'", end = "'", close = true, newline = false },
]
